services:
  - type: web
    name: myapp
    env: python
    buildCommand: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      source venv/bin/activate
      gunicorn -b 0.0.0.0:$PORT app.app:app
    plan: free
